# Generated by Django 6.0.2 on 2026-02-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('biography', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('nationality', models.CharField(max_length=200)),
            ],
        ),
    ]
